name: "Publish"
on:
  # Run only when pushing to master branch
  push:
    branches:
      - master
jobs:
  neuron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download neuron
      run: |
        curl --silent https://api.github.com/repos/srid/neuron/actions/artifacts \
          | jq 'first(.artifacts | .[] | select(.name == "neuron-bundle-linux") | .archive_download_url)' -r \
          | xargs curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" --silent -L -o neuron-bundle-linux.zip
        unzip neuron-bundle-linux.zip
        chmod +x neuron
        ./neuron --version  # This extracts the bundle; should take a while
    - name: Build neuron site 🔧
      run: |
        ./neuron -d ${PWD}/guide rib
    - name: Deploy to gh-pages 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./guide/.neuron/output/
        cname: ka.srid.ca
